framework:
    test: true
    secret: '%env(APP_SECRET)%'
    # ...
    router:
        utf8: true
    session:
        handler_id: null
        cookie_secure: auto
    default_locale: en
    csrf_protection: true
    http_method_override: true
    # ...
    error_controller: null
